### PR TITLE
Periodic domains

### PR DESCRIPTION
**Pull request by holl-**
Version Highlights:
- Periodic pressure solve
- Improved structs: `content_type`, global item context, batched structs

Breaking Changes:
- (minor) Removed `item_condition` argument from `placeholder()`. Use the context item condition instead.
- (minor) `CenteredGrid.dtype` now returns a `CenteredGrid`. Same for `StaggeredGrid`.
- (minor) Passing `item_condition=None` anywhere now uses the context item condition. Use `item_condition=ALL_ITEMS` to iterate over all items.
- (minor) `StructBackend` now validates returned values by default. Replace it with  `StructBackend(target_content_type=struct.INVALID)` to revert to old behavior.

Deprecations:
- `math.types`: Use `Struct.dtype` instead.
- `StateCollection.default_physics`
- `struct.unsafe()`: Set `content_type` to non-data instead.

### CODE REVIEW

**Comment by the-rccg** [comment]
In my tests, I am unable to get the dtype of a CenteredGrid returned using the .dtype
```python
>>> CenteredGrid([[1,2,3,4]]).dtype
CenteredGrid[<function dtype at 0x000001AECF918438>]
```
Given that CenteredGrid.dtype is a CenteredGrid, in theory CenteredGrid.dtype.dtype should be a valid operation, which it is not: `AssertionError: dtype can only be accessed on data structs but 'CenteredGrid' has content type '<function dtype at 0x000001AECF918438>'`
One suggested return might be the Python `type` class, which is returned when doing things like:
```python
>>> type(type(np.array([1,2,3,4]).dtype))
<class 'type'>
```

**Comment by holl-** [comment]
To get the dtype of data, use one of the following:
```python
>>> CenteredGrid([[1,2,3,4]]).dtype.data
int64
>>> CenteredGrid([[1,2,3,4]]).data.dtype
int64
```
Calling `dtype` on a `dtype` struct is almost certainly a bug in the code. I cannot think of a good use for this so I made it illegal. Calling `np.array([1,2,3,4]).dtype.dtype` raises an `AttributeError` so maybe we should do that as well.
If you are really interested in the types of dtype, use
```python
>>> math.types(CenteredGrid([[1,2,3,4]]).dtype).data
<class 'numpy.dtype'>
```

**Comment by the-rccg** [comment]
That makes sense. The analogy to numpy breaks here, as numpyp.array.dtype is not a numpy.array but a numpy.dtype class. Just to clarify, I am not in favor of making a new class. I think a more direct error message might be helpful like "AssertionError: accessing dtype of dtype is an invalid operation" which helps debug code where someone might access the data types twice accidentally.

**Comment by the-rccg** [comment]
On a more general basis, it seems to be that properties like rank implicitly access CenteredGrid.data to return the values directly, while methods e.g. gradient() acess CenteredGrid.data to return a CenteredGrid. Intuitively I'd expect .dtype to work like a property and directly return the values like rank, rather than act like a method and return a CenteredGrid

**Comment by holl-** [comment]
Previously, CenteredGrid.dtype would return the data type of `data` directly, not a CenteredGrid.

However, the properties `dtype`, `shape` and `staticshape` are now defined in `Struct` and should be consistent among all structs.
This new unified system is much more powerful as it allows you (i) to use the properties on more complex structs such as `Fluid` and (ii) to specify of which items you want the property by specifying it in the item context.

For example
```python
with struct.CONSTANTS:
    constant_types = grid.dtype
```
will fetch the types of constants such as `extrapolation` instead of `data`.

**Comment by the-rccg** [comment]
That makes sense. I'm happy to approve the merge as soon as this behavior is documented since it is both new in this version and not intuitive, but powerful once understood.

**Pull request merged**
